const fs = require("fs");
const content = [
  "import React, { useState, useEffect } from 'react'",
  "import { Link, useNavigate } from 'react-router-dom'",
  "import { motion } from 'framer-motion'",
  "import { Clock, Heart, Edit2, Trash2, Star, Share2, ChefHat } from 'lucide-react'",
  "import axios from 'axios'",
  "import toast from 'react-hot-toast'",
  "import { useAuth } from '../context/AuthContext'",
  "",
  "const API = import.meta.env.VITE_API_URL || 'http://localhost:5000'",
  "",
  "function getImgSrc(coverImage) {",
  "  if (!coverImage) return 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80'",
  "  if (coverImage.startsWith('http')) return coverImage",
  "  return API + '/images/' + coverImage",
  "}",
  "",
  "export default function RecipeCard({ item, isOwner = false, onDelete, favIds = [] }) {",
  "  const navigate = useNavigate()",
  "  const { isLoggedIn, token } = useAuth()",
  "  const [isFav, setIsFav] = useState(() => favIds.includes(item._id))",
  "  const [favLoading, setFavLoading] = useState(false)",
  "",
  "  useEffect(() => {",
  "    setIsFav(favIds.includes(item._id))",
  "  }, [favIds, item._id])",
  "",
  "  const toggleFav = async (e) => {",
  "    e.stopPropagation()",
  "    if (!isLoggedIn) { toast.error('Please sign in to favourite recipes'); return }",
  "    setFavLoading(true)",
  "    try {",
  "      const res = await axios.put(",
  "        API + '/recipe/' + item._id + '/favorite',",
  "        {},",
  "        { headers: { authorization: 'bearer ' + token } }",
  "      )",
  "      setIsFav(res.data.isFav)",
  "      toast(res.data.isFav ? 'Added to favourites! \u2764\ufe0f' : 'Removed from favourites', {",
  "        icon: res.data.isFav ? '\u2764\ufe0f' : '\uD83D\uDC94'",
  "      })",
  "    } catch {",
  "      toast.error('Failed to update favourites')",
  "    } finally {",
  "      setFavLoading(false)",
  "    }",
  "  }",
  "",
  "  const handleDelete = async (e) => {",
  "    e.stopPropagation()",
  "    if (!window.confirm('Delete this recipe?')) return",
  "    try {",
  "      await axios.delete(API + '/recipe/' + item._id, {",
  "        headers: { authorization: 'bearer ' + token }",
  "      })",
  "      toast.success('Recipe deleted')",
  "      onDelete?.(item._id)",
  "    } catch (err) {",
  "      toast.error(err.response?.data?.message || 'Failed to delete recipe')",
  "    }",
  "  }",
  "",
  "  const handleShare = (e) => {",
  "    e.stopPropagation()",
  "    const url = window.location.origin + '/recipe/' + item._id",
  "    if (navigator.share) {",
  "      navigator.share({ title: item.title, url })",
  "    } else {",
  "      navigator.clipboard.writeText(url)",
  "      toast.success('Link copied to clipboard!')",
  "    }",
  "  }",
  "",
  "  const rating = item.rating || 4.0",
  "",
  "  return (",
  "    <motion.div",
  "      className='recipe-card'",
  "      initial={{ opacity: 0, y: 20 }}",
  "      animate={{ opacity: 1, y: 0 }}",
  "      whileHover={{ y: -6, transition: { duration: 0.2 } }}",
  "      transition={{ duration: 0.3 }}",
  "      onClick={() => navigate('/recipe/' + item._id)}",
  "    >",
  "      <div className='recipe-card__img-wrap'>",
  "        <img",
  "          src={getImgSrc(item.coverImage)}",
  "          alt={item.title}",
  "          className='recipe-card__img'",
  "          onError={e => { e.target.src = 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80' }}",
  "        />",
  "        <div className='recipe-card__overlay' />",
  "        <div className='recipe-card__top'>",
  "          {item.time && (",
  "            <span className='recipe-card__badge'>",
  "              <Clock size={12} /> {item.time}",
  "            </span>",
  "          )}",
  "          {item.category && item.category !== 'General' && (",
  "            <span className='recipe-card__badge recipe-card__badge--cat'>{item.category}</span>",
  "          )}",
  "        </div>",
  "        <div className='recipe-card__actions'>",
  "          {!isOwner && (",
  "            <motion.button",
  "              className={'recipe-card__action-btn' + (isFav ? ' recipe-card__action-btn--fav' : '')}",
  "              onClick={toggleFav}",
  "              whileTap={{ scale: 0.85 }}",
  "              disabled={favLoading}",
  "              title={isFav ? 'Remove from favourites' : 'Add to favourites'}",
  "            >",
  "              <Heart size={16} fill={isFav ? '#f97316' : 'none'} />",
  "            </motion.button>",
  "          )}",
  "          <motion.button className='recipe-card__action-btn' onClick={handleShare} whileTap={{ scale: 0.85 }} title='Share recipe'>",
  "            <Share2 size={15} />",
  "          </motion.button>",
  "        </div>",
  "      </div>",
  "      <div className='recipe-card__body'>",
  "        <div className='recipe-card__meta'>",
  "          <div className='recipe-card__rating'>",
  "            <Star size={13} fill='#f97316' color='#f97316' />",
  "            <span>{Math.min(rating, 5).toFixed(1)}</span>",
  "          </div>",
  "          <span className='recipe-card__ingredients-count'>",
  "            <ChefHat size={13} />",
  "            {item.ingredients?.length || 0} ingredients",
  "          </span>",
  "        </div>",
  "        <h3 className='recipe-card__title'>{item.title}</h3>",
  "        {isOwner && (",
  "          <div className='recipe-card__owner-actions' onClick={e => e.stopPropagation()}>",
  "            <Link to={'/editRecipe/' + item._id} className='recipe-card__edit-btn'>",
  "              <Edit2 size={14} /> Edit",
  "            </Link>",
  "            <button className='recipe-card__delete-btn' onClick={handleDelete}>",
  "              <Trash2 size={14} /> Delete",
  "            </button>",
  "          </div>",
  "        )}",
  "      </div>",
  "    </motion.div>",
  "  )",
  "}"
].join("\n");
fs.writeFileSync("foodRecipe/frontend/food-blog-app/src/components/RecipeCard.jsx", content, "utf8");
console.log("RecipeCard.jsx written");
