const fs = require("fs");
const content = [
  "import React, { useState, useEffect } from 'react'",
  "import RecipeCard from './RecipeCard'",
  "import { motion } from 'framer-motion'",
  "import axios from 'axios'",
  "import { useAuth } from '../context/AuthContext'",
  "",
  "const API = import.meta.env.VITE_API_URL || 'http://localhost:5000'",
  "",
  "export default function RecipeItems({ recipes, isOwner = false }) {",
  "  const [items, setItems] = useState(recipes || [])",
  "  const [favIds, setFavIds] = useState([])",
  "  const { isLoggedIn, token } = useAuth()",
  "",
  "  useEffect(() => { setItems(recipes || []) }, [recipes])",
  "",
  "  // Fetch user's favorite IDs from backend",
  "  useEffect(() => {",
  "    if (!isLoggedIn || !token) { setFavIds([]); return }",
  "    axios.get(API + '/recipe/my/favorites', {",
  "      headers: { authorization: 'bearer ' + token }",
  "    })",
  "      .then(res => setFavIds((res.data || []).map(r => r._id)))",
  "      .catch(() => setFavIds([]))",
  "  }, [isLoggedIn, token])",
  "",
  "  const handleDelete = (id) => setItems(prev => prev.filter(r => r._id !== id))",
  "",
  "  if (!items.length) {",
  "    return (",
  "      <div className='empty-state'>",
  "        <span className='empty-state__emoji'>🍽️</span>",
  "        <h3>No recipes yet</h3>",
  "        <p>Be the first to share a delicious recipe!</p>",
  "      </div>",
  "    )",
  "  }",
  "",
  "  return (",
  "    <motion.div",
  "      className='recipe-grid'",
  "      initial='hidden'",
  "      animate='visible'",
  "      variants={{ hidden: {}, visible: { transition: { staggerChildren: 0.07 } } }}",
  "    >",
  "      {items.map(item => (",
  "        <RecipeCard",
  "          key={item._id}",
  "          item={item}",
  "          isOwner={isOwner}",
  "          onDelete={handleDelete}",
  "          favIds={favIds}",
  "        />",
  "      ))}",
  "    </motion.div>",
  "  )",
  "}"
].join("\n");
fs.writeFileSync("foodRecipe/frontend/food-blog-app/src/components/RecipeItems.jsx", content, "utf8");
console.log("RecipeItems.jsx written");
