const fs = require("fs");
const content = [
  "import React from 'react'",
  "import './App.css'",
  "import { createBrowserRouter, RouterProvider } from 'react-router-dom'",
  "import Home from './pages/Home'",
  "import MainNavigation from './components/MainNavigation'",
  "import axios from 'axios'",
  "import AddFoodRecipe from './pages/AddFoodRecipe'",
  "import EditRecipe from './pages/EditRecipe'",
  "import RecipeDetails from './pages/RecipeDetails'",
  "",
  "const API = import.meta.env.VITE_API_URL || 'http://localhost:5000'",
  "",
  "const authHeaders = () => ({",
  "  headers: { authorization: 'bearer ' + localStorage.getItem('token') }",
  "})",
  "",
  "// ── Loaders ──────────────────────────────────────────────────────────────────",
  "const getAllRecipes = async () => {",
  "  try {",
  "    const res = await axios.get(API + '/recipe')",
  "    return res.data || []",
  "  } catch { return [] }",
  "}",
  "",
  "const getMyRecipes = async () => {",
  "  try {",
  "    const token = localStorage.getItem('token')",
  "    if (!token) return []",
  "    const res = await axios.get(API + '/recipe/my/recipes', authHeaders())",
  "    return res.data || []",
  "  } catch { return [] }",
  "}",
  "",
  "const getFavRecipes = async () => {",
  "  try {",
  "    const token = localStorage.getItem('token')",
  "    if (!token) return []",
  "    const res = await axios.get(API + '/recipe/my/favorites', authHeaders())",
  "    return res.data || []",
  "  } catch { return [] }",
  "}",
  "",
  "const getRecipe = async ({ params }) => {",
  "  try {",
  "    const recipeRes = await axios.get(API + '/recipe/' + params.id)",
  "    let recipe = recipeRes.data",
  "    try {",
  "      const userRes = await axios.get(API + '/user/' + recipe.createdBy)",
  "      recipe = { ...recipe, email: userRes.data.email }",
  "    } catch { }",
  "    return recipe",
  "  } catch { return null }",
  "}",
  "",
  "const router = createBrowserRouter([",
  "  { path: '/', element: <MainNavigation />, children: [",
  "    { path: '/',           element: <Home />,         loader: getAllRecipes },",
  "    { path: '/myRecipe',   element: <Home />,         loader: getMyRecipes },",
  "    { path: '/favRecipe',  element: <Home />,         loader: getFavRecipes },",
  "    { path: '/addRecipe',  element: <AddFoodRecipe /> },",
  "    { path: '/editRecipe/:id', element: <EditRecipe /> },",
  "    { path: '/recipe/:id', element: <RecipeDetails />, loader: getRecipe }",
  "  ]}",
  "])",
  "",
  "export default function App() {",
  "  return <RouterProvider router={router} />",
  "}"
].join("\n");
fs.writeFileSync("foodRecipe/frontend/food-blog-app/src/App.jsx", content, "utf8");
console.log("App.jsx written");
