const fs = require("fs");
const lines = [
  "const Recipes = require('../models/recipe')",
  "const User    = require('../models/user')",
  "const multer  = require('multer')",
  "const path    = require('path')",
  "",
  "// ── Multer setup ────────────────────────────────────────────────────────────",
  "const storage = multer.diskStorage({",
  "  destination: (req, file, cb) => cb(null, './public/images'),",
  "  filename:    (req, file, cb) => cb(null, Date.now() + '-' + file.fieldname)",
  "})",
  "const upload = multer({ storage })",
  "",
  "// ── GET /recipe  →  all recipes ─────────────────────────────────────────────",
  "const getRecipes = async (req, res) => {",
  "  try {",
  "    const recipes = await Recipes.find().sort({ createdAt: -1 })",
  "    res.json(recipes)",
  "  } catch (err) {",
  "    res.status(500).json({ message: err.message })",
  "  }",
  "}",
  "",
  "// ── GET /recipe/my  →  only logged-in user's recipes ────────────────────────",
  "const getMyRecipes = async (req, res) => {",
  "  try {",
  "    const recipes = await Recipes.find({ createdBy: req.user.id }).sort({ createdAt: -1 })",
  "    res.json(recipes)",
  "  } catch (err) {",
  "    res.status(500).json({ message: err.message })",
  "  }",
  "}",
  "",
  "// ── GET /recipe/favorites  →  user's favorited recipes ──────────────────────",
  "const getFavorites = async (req, res) => {",
  "  try {",
  "    const user = await User.findById(req.user.id).populate('favorites')",
  "    if (!user) return res.status(404).json({ message: 'User not found' })",
  "    res.json(user.favorites || [])",
  "  } catch (err) {",
  "    res.status(500).json({ message: err.message })",
  "  }",
  "}",
  "",
  "// ── PUT /recipe/:id/favorite  →  toggle favorite ────────────────────────────",
  "const toggleFavorite = async (req, res) => {",
  "  try {",
  "    const user = await User.findById(req.user.id)",
  "    if (!user) return res.status(404).json({ message: 'User not found' })",
  "",
  "    const recipeId = req.params.id",
  "    const idx = user.favorites.findIndex(id => id.toString() === recipeId)",
  "",
  "    let isFav",
  "    if (idx === -1) {",
  "      user.favorites.push(recipeId)",
  "      isFav = true",
  "    } else {",
  "      user.favorites.splice(idx, 1)",
  "      isFav = false",
  "    }",
  "    await user.save()",
  "    res.json({ isFav, favoritesCount: user.favorites.length })",
  "  } catch (err) {",
  "    res.status(500).json({ message: err.message })",
  "  }",
  "}",
  "",
  "// ── GET /recipe/:id  →  single recipe ───────────────────────────────────────",
  "const getRecipe = async (req, res) => {",
  "  try {",
  "    const recipe = await Recipes.findById(req.params.id)",
  "    if (!recipe) return res.status(404).json({ message: 'Recipe not found' })",
  "    res.json(recipe)",
  "  } catch (err) {",
  "    res.status(500).json({ message: err.message })",
  "  }",
  "}",
  "",
  "// ── POST /recipe  →  create recipe ──────────────────────────────────────────",
  "const addRecipe = async (req, res) => {",
  "  try {",
  "    const { title, ingredients, instructions, time, description, category, difficulty } = req.body",
  "    if (!title || !ingredients || !instructions)",
  "      return res.status(400).json({ message: \"Required fields can't be empty\" })",
  "",
  "    const coverImage = req.file ? req.file.filename : (req.body.coverImage || '')",
  "    const newRecipe = await Recipes.create({",
  "      title, ingredients, instructions, time,",
  "      description: description || '',",
  "      category:    category    || 'General',",
  "      difficulty:  difficulty  || 'Medium',",
  "      coverImage,",
  "      createdBy: req.user.id",
  "    })",
  "    res.json(newRecipe)",
  "  } catch (err) {",
  "    res.status(500).json({ message: err.message })",
  "  }",
  "}",
  "",
  "// ── PUT /recipe/:id  →  edit recipe (owner only) ────────────────────────────",
  "const editRecipe = async (req, res) => {",
  "  try {",
  "    const recipe = await Recipes.findById(req.params.id)",
  "    if (!recipe) return res.status(404).json({ message: 'Recipe not found' })",
  "    if (recipe.createdBy.toString() !== req.user.id)",
  "      return res.status(403).json({ message: 'Not authorized to edit this recipe' })",
  "",
  "    const coverImage = req.file ? req.file.filename : recipe.coverImage",
  "    const updated = await Recipes.findByIdAndUpdate(",
  "      req.params.id,",
  "      { ...req.body, coverImage },",
  "      { new: true }",
  "    )",
  "    res.json(updated)",
  "  } catch (err) {",
  "    res.status(500).json({ message: err.message })",
  "  }",
  "}",
  "",
  "// ── DELETE /recipe/:id  →  delete recipe (owner only) ───────────────────────",
  "const deleteRecipe = async (req, res) => {",
  "  try {",
  "    const recipe = await Recipes.findById(req.params.id)",
  "    if (!recipe) return res.status(404).json({ message: 'Recipe not found' })",
  "    if (recipe.createdBy.toString() !== req.user.id)",
  "      return res.status(403).json({ message: 'Not authorized to delete this recipe' })",
  "",
  "    await Recipes.deleteOne({ _id: req.params.id })",
  "    // Remove from all users' favorites",
  "    await User.updateMany({}, { $pull: { favorites: req.params.id } })",
  "    res.json({ status: 'ok', message: 'Recipe deleted' })",
  "  } catch (err) {",
  "    res.status(400).json({ message: err.message })",
  "  }",
  "}",
  "",
  "module.exports = { getRecipes, getMyRecipes, getFavorites, toggleFavorite, getRecipe, addRecipe, editRecipe, deleteRecipe, upload }"
];
fs.writeFileSync("foodRecipe/backend/controller/recipe.js", lines.join("\n"), "utf8");
console.log("recipe controller written, lines:", lines.length);
